export * from "./type"
export * from "./iteratorableItemAndEntry" // Item 和 Entriable 体系
export * from "./concat"
export * from "./drop"
export * from "./every"
export * from "./filter"
export * from "./find"
export * from "./forEach"
export * from "./groupBy"
export * from "./insert"
export * from "./map"
export * from "./reduce"
// TODO isolate flatMap() (2022-06-10)
export * from "./shakeNil"
// TODO: changeCollectionType: (oldCollection, targetType: 'array' | 'object' | 'set' | 'map') => newCollection
export * from "./omit"
export * from "./pick"
export * from "./itemMethods"
export * from "./take"
export * from "./iteratorableUtils"
