import { getType } from './dataType'

test('all build-in type ', () => {
  expect(getType([1, 2])).toEqual('Array')
  expect(getType(null)).toEqual('null')
  expect(getType(undefined)).toEqual('undefined')
  expect(getType(true)).toEqual('boolean')
  expect(getType(3)).toEqual('number')
  expect(getType('xxx')).toEqual('string')
  expect(getType(11n)).toEqual('bigint')
  expect(getType(Symbol.for('hello'))).toEqual('symbol')
  expect(getType(() => {})).toEqual('function')
  expect(getType([])).toEqual('Array')
  expect(getType(new Set())).toEqual('Set')
  expect(getType(new Map())).toEqual('Map')
  expect(getType(new WeakSet())).toEqual('WeakSet')
  expect(getType(new WeakMap())).toEqual('WeakMap')
  expect(getType({})).toEqual('Object')
  expect(getType(Object.create(null))).toEqual('Object')
  expect(getType(new Date())).toEqual('Date')
})
